[tasks.fix]
install_crate = "rustfmt"
command = "cargo"
args = ["fix", "--allow-dirty", "--all-features"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.build-wasm]
command = "cargo"
args = ["build", "--release"]
dependencies = ["clean"]

[tasks.install]
command = "cargo"
args = ["install", "--path", "."]

[tasks.rua]
dependencies = ["fix", "format", "test", "build"]
